services:
  # 反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  # 前端: React
  frontend:
    build: 
      context: ./frontend
    restart: unless-stopped

  # 後端: Spring-Boot
  backend:
    depends_on:
      db:
        condition: service_healthy
    build: ./backend
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${DOCKER_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DOCKER_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DOCKER_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=production  
    restart: unless-stopped

  # 資料庫: MySQL
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=myjdbc
      - MYSQL_ROOT_PASSWORD=${DOCKER_DATASOURCE_PASSWORD} 
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DOCKER_DATASOURCE_PASSWORD}"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

volumes:
  mysql_data: